### ISSUE TITLE
Add to Jay's 'cleaning' file 

### ISSUE THREAD

**Issue by egipe** [Gnosder/group_bestest_guys#7]
# create new column
tweet_df['sentiment_category'] = ''
tweet_df['word_count']= ''
tweet_df['word_count'] = tweet_df['scores_only'].str.len()

# assign sentiment category
tweet_df.loc[tweet_df.avg_scores >= 5.5, 'sentiment_category'] = 'positive'
tweet_df.loc[(tweet_df.avg_scores > 5) & (tweet_df.avg_scores < 5.5), 'sentiment_category'] = 'neutral'
tweet_df.loc[tweet_df.avg_scores <= 5 , 'sentiment_category'] = 'negative'

tweet_df.head()

**Comment by jaysueno** [comment]
included in notebook

**Comment by jaysueno** [comment]
closed
